
services:

  postgres_db:
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
        - fest_connect_network

  # Configuracao do Jaeger para coleta de traces
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Interface Web (UI)
      - "4317:4317"   # Porta para receber traces via gRPC (OpenTelemetry)
      - "4318:4318"   # Porta para receber traces via HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  # Configuracao do Prometheus para coleta de métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Injeta o arquivo que criamos
    extra_hosts:
      - "host.docker.internal:host-gateway" # Permite acesso ao Windows

  # Configuracao do Grafana para visualizacao de métricas e traces
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Senha padrão para logar
    depends_on:
      - prometheus

  backend_api_fest_connect:
    build:
      context: .
    container_name: api-fest-connect
    ports:
      - "8080:8080"
    env_file:
      - ".env"
    depends_on:
      - postgres_db
    networks:
      - fest_connect_network

networks:
  fest_connect_network:
    driver: bridge
