# Dev Profile Configuration

# PostgreSQL Database Connection
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres_db:5432/festconnectdb}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracoes do Amazon S3 DEV
aws.s3.access-key=${ACCESS_KEY_S3:dev-dummy-key}
aws.s3.secret-key=${SECRET_KEY_S3:dev-dummy-secret}
aws.s3.region=${BUCKET_REGION_S3:us-east-1}
aws.s3.bucket-name=${BUCKET_NAME_S3:dev-dummy-bucket}

# Upload de midias
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

management.endpoints.web.exposure.include=health,info

api.security.token.secret=${SECRET_KEY_TOKEN:api-party-chave-secreta-local}

# Configuracoes de email para desenvolvimento (usando Mailtrap)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_TRAP_USERNAME:4dfbcb45722131}
spring.mail.password=${MAIL_TRAP_SENHA:6b9377b5382b6f}

# Configuracoes do Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# URL do frontend (para o redirect pós-OAuth2)
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
